### ISSUE TITLE
Output file types

### ISSUE THREAD

**Issue by jayvdb** [ahmet2mir/wildq#1]
It would be helpful to be able to emit the output in the same format as the input, or other formats.

**Comment by ahmet2mir** [comment]
Hello,

Yes it will :)
I will rework on the code in next weeks.
Keep you in touch.

Le mar. 11 août 2020 à 07:25, John Vandenberg <notifications@github.com> a
écrit :

**Comment by ahmet2mir** [comment]
@jayvdb  after fighting with github actions, you could upgrade via pip to v1.1.0  or use the binary version.
