### ISSUE TITLE
Update to `click 8`

### ISSUE THREAD

**Issue by JeppeKlitgaard** [ahmet2mir/wildq#11]
I am trying to use `wildq` in a project that also depends on `black`, which requires `click >= 8.0.0` for current versions.

Would it be possible to update `wildq` to use `click 8` or relax the dependency version constraint?

**Comment by ahmet2mir** [comment]
Hello @JeppeKlitgaard 

I was certain that i answered to this question via mail, it seems not.

Since april do you still need this ? I prefer to "relax" as i don't use advanced features inside wq.

**Comment by JeppeKlitgaard** [comment]
I found a different approach that ended up solving my problem. Feel free to close this!
