### ISSUE TITLE
Combine options do not work as advertised

### ISSUE THREAD

**Issue by rainyday** [ahmet2mir/wildq#3]
### Wildq Version
1.1.7

### Affected FileType(s)
All except JSON

### Expected Behavior
According to the documentation, using one of the combine options should output in the same format as the output (eg `--yaml` should take a yaml input and produce a yaml output, being equivalent to `wildq -i yaml -o yaml ...`)

### Actual Behavior
The output is always JSON

### Steps to Reproduce
`wildq --yaml . file.yml` or any other option such as `--toml`, `--xml` etc.

**Comment by ahmet2mir** [comment]
Hello,

It could be a bit confusing for new users. 

They were no -i/-o in previous version, for backward compatibility in previous version only --[yaml|json|toml|ini|xml|hcl] was possible with default to json output. We still keep Monochrome, raw and json output with thoses options. Output was similar to jq -MCr (no color, no compact and no quote on single value)

In the cli output you could see for toml for example  

> "Combine --input toml --output json" 

But If you use -i yaml the output will be yaml too. 

Could you tell which part in the doc must be enhanced ? To be more explicit ? As author is not always easy to make clear doc :)

**Comment by ahmet2mir** [comment]
Got it. Readme help is different than CLI.
Thanks for reporting it.
Will fix.

**Comment by ahmet2mir** [comment]
Fixed in release https://github.com/ahmet2mir/wildq/releases/tag/v1.1.8

**Comment by rainyday** [comment]
Looks good!

**Comment by ahmet2mir** [comment]
@rainyday thanks for your issue, don't hesitate to create issue for new features, star if you like wildq and tell your friends :)
