### ISSUE TITLE
Question: why use Jq ?

### ISSUE THREAD

**Issue by Djabx** [ahmet2mir/wildq#4]
Hi there,

Why do you bother with `jq` lib and not just convert from a format to another ?
I think the purpose of the application would be clearer and more inline with unix (aka `Make each program do one thing well.` )

Moreover I think it would be clearer and easier to manipulate; and the user will be able to upgrade `jq` as they need.

Usage would be something like that:

```shell
cat examples/ini.ini | wildq -i init | jq ".keys" | wildq -i json -o json
```

**Comment by ahmet2mir** [comment]
Hello @Djabx,

wildq uses existing libs (don't reinvent the wheel) which are maintained by their respective developers.
wildq only wrap them into single interface which is not "against" unix philophy.

Like grep + wc
```
grep key examples/ini.ini| wc -l
```

become

```
grep -c key examples/ini.ini 
```

For your example you could also do

```
wq --ini . examples/ini.ini | jq ".keys" | wq -i json -o yaml  .
```

which become

```
wq -i ini -o yaml .keys examples/ini.ini
```

Of course I could split the project into 2 one without jq and keep wildq with jq.

Thanks for your feedback, will consider it.
