### ISSUE TITLE
Update toml dep to 0.10.2

### ISSUE THREAD

**Issue by johnklehm** [ahmet2mir/wildq#6]
Some toml files aren't handled right now. Updating this dep will fix it.

**Comment by ahmet2mir** [comment]
Hello @johnklehm 

Thanks for the report. Do you have some failing toml so I could test them ?

**Comment by johnklehm** [comment]
Away from my primary machine, I'll follow up later with the exact file.  Format was a pyproject.toml file, something along the lines of:
```
[tools.poetry]
name = "the name"
description = ""
authors  = [
   "author one",
   "author two",
   "author three"
]
```
The line number of the failure was the authors line.

**Comment by johnklehm** [comment]
Related commit from `toml` here: https://github.com/uiri/toml/commit/30267db1522e3371c5ebc5d131ef6a8a09e50d8c

**Comment by ahmet2mir** [comment]
I tested with the current version and it works

```
$ wq --version
wq, version 1.1.8

$ cat > test.toml
[project]
name = "the name"
description = ""
authors  = [
   "author one",
   "author two",
   "author three"
]
^C

$ wq --toml . test.toml 
{
    "project": {
        "name": "the name",
        "description": "",
        "authors": [
            "author one",
            "author two",
            "author three"
        ]
    }
}

$ wq -i toml . test.toml 
[project]
name = "the name"
description = ""
authors = [ "author one", "author two", "author three",]
```

Anyway, upgraded tom packagel in [v1.1.10](https://github.com/ahmet2mir/wildq/releases/tag/v1.1.10), let me know if it fix your issue ?

**Comment by johnklehm** [comment]
Yup thanks!
