### ISSUE TITLE
Brew tap is broken

### ISSUE THREAD

**Issue by ira-bv** [ahmet2mir/wildq#8]
I get this error with every Brew command:

```
=> brew uninstall spaceship
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the ahmet2mir/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/ahmet2mir/homebrew-tap/Formula/wq.rb:7

Uninstalling /usr/local/Cellar/spaceship/3.16.3... (55 files, 124.4KB)
```

I finally removed wq, untapped and used pip install, but this should be easy to fix. thanks!

**Comment by ahmet2mir** [comment]
Hello @ira-bv,

Thanks for report, removed the deprecated option https://github.com/ahmet2mir/homebrew-tap/commit/6fd65f5775c4049c20b500db85190fdf31103bf5

**Comment by ahmet2mir** [comment]
@ira-bv  no news since september, I'm closing, this issue, reopen if needed.
